const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const API=location.origin, USER=localStorage.getItem('spartan_user')||'demo-spartan', ORG='demo-company';
let projectId=localStorage.getItem('spartan_project')||null, askMode='auto', currentThread=null, activePath=null;

async function api(path,opts={}){const r=await fetch(API+path,{headers:{...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opts.headers||{})},...opts});if(!r.ok)throw new Error((await r.text())||`${r.status}`);const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),2600)}
function fmtPct(n){return `${Math.round((Number(n)||0)*100)}%`}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='knowledge')loadKnowledge();if(view==='paths')loadPaths();if(view==='team')loadTeam();if(view==='engineering')loadEngineering();}
$$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.view));$$('[data-go]').forEach(n=>n.onclick=()=>go(n.dataset.go));

function modal(id,show=true){$(id).classList.toggle('hidden',!show)}
$$('.modal-close').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').classList.add('hidden'));
$$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));

async function ensureProject(){let projects=await api(`/api/projects?org_id=${ORG}`);if(!projects.length){const p=await api('/api/projects',{method:'POST',body:JSON.stringify({org_id:ORG,user_id:USER,name:'Engineering Platform',description:'Private engineering onboarding workspace'})});projects=[p]}
 if(!projectId||!projects.some(p=>p.id===projectId))projectId=projects[0].id;localStorage.setItem('spartan_project',projectId);const sel=$('#projectSelect');sel.innerHTML=projects.map(p=>`<option value="${p.id}" ${p.id===projectId?'selected':''}>${esc(p.name)}</option>`).join('');sel.onchange=()=>{projectId=sel.value;localStorage.setItem('spartan_project',projectId);refreshAll()}}

async function health(){try{const h=await api('/api/health');const online=Object.values(h.model_endpoints||{}).some(Boolean);$('#modelState').textContent=online?'DGX Spark · local models online':'DGX Spark · app online, models warming';$('#modelState').style.color=online?'#238636':'#8a6d00'}catch{$('#modelState').textContent='Backend offline'}}

async function loadHome(){if(!projectId)return;try{const [map,paths,resume,stats]=await Promise.all([api(`/api/projects/${projectId}/map`),api(`/api/onboarding/${projectId}?user_id=${USER}`),api(`/api/resource/resume/${USER}?project_id=${projectId}`),api('/api/admin/stats')]);$('#heroDocs').textContent=map.documents||0;$('#symbolCount').textContent=(map.symbols||[]).length;$('#languageMap').innerHTML=Object.entries(map.languages||{}).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([x,n])=>`<span class="lang">${esc(x)} · ${n}</span>`).join('')||'<span class="lang">Connect a repository</span>';renderResume(resume);renderMiniLeaderboard(stats.leaderboard||[]);if(paths.length){activePath=await api(`/api/onboarding/path/${paths[0].id}?user_id=${USER}`);renderHomePath(activePath)}else renderHomePath(null);const traces=await api('/api/admin/traces?limit=1');if(traces[0]?.latency_ms)$('#heroLatency').textContent=`${(traces[0].latency_ms/1000).toFixed(1)}s`}catch(e){console.error(e)}}
function renderResume(items){const el=$('#resumeCards');const colors=['#eeeeff','#e7f4ff','#eef8ef'];if(!items.length){el.innerHTML=`<article class="resume-card" style="--tint:#eeeeff"><span class="type">Browser memory</span><h3>Your continuation cards will appear here.</h3><p>The Chrome companion tracks learning progress without treating time-on-page as mastery.</p></article>`;return}el.innerHTML=items.slice(0,3).map((r,i)=>`<article class="resume-card" style="--tint:${colors[i%3]}"><span class="type">${esc(r.resource_type||'resource')} · ${Math.round((r.progress||0)*100)}%</span><h3>${esc(r.resource_title||r.resource_url)}</h3><p>${esc(r.summary||'Continue from your last active position. A recap will be generated as context becomes available.')}</p><div class="resume-meta"><span>${Math.round((r.seconds_active||0)/60)} min active</span><b>${r.last_position?`Resume ${Math.floor(r.last_position/60)}:${String(Math.floor(r.last_position%60)).padStart(2,'0')}`:'Continue →'}</b></div></article>`).join('')}
function renderMiniLeaderboard(rows){const html=rows.slice(0,5).map((r,i)=>`<div class="rank"><span class="num">${i+1}</span><div><strong>${esc(r.display_name||'Learner')}</strong><small>${fmtPct(r.progress||0)} readiness progress</small></div><b>${r.xp||0} XP</b></div>`).join('')||'<div class="rank"><span class="num">1</span><div><strong>Invite your team</strong><small>Leaderboard starts with meaningful checkpoints</small></div><b>0 XP</b></div>';$('#leaderboardMini').innerHTML=html;$('#leaderboardFull').innerHTML=html}
function renderHomePath(p){if(!p){$('#activePathTitle').textContent='Generate a role-based path';$('#progressScore').textContent='0%';$('#progressBar').style.width='0';$('#nextTasks').innerHTML='<div class="task"><span class="check">→</span><div><b>Connect knowledge and generate onboarding</b><small>StudyBuddy will map prerequisites to the actual repository.</small></div></div>';return}const me=(p.members||[]).find(x=>x.user_id===USER)||{};$('#activePathTitle').textContent=p.title;$('#progressScore').textContent=fmtPct(me.progress||0);$('#progressBar').style.width=fmtPct(me.progress||0);const done=new Set((p.progress_items||[]).filter(x=>x.status==='completed').map(x=>x.item_id));const items=(p.plan.modules||[]).flatMap(m=>m.items||[]).filter(x=>!done.has(x.id)).slice(0,3);$('#nextTasks').innerHTML=items.map(x=>`<div class="task"><span class="check">${esc(x.type==='checkpoint'?'✓':'→')}</span><div><b>${esc(x.title)}</b><small>${x.minutes||15} min · +${x.xp||100} XP</small></div></div>`).join('')||'<div class="task"><span class="check">✓</span><div><b>Path complete</b><small>Ask your manager for the next milestone.</small></div></div>'}

async function loadKnowledge(){if(!projectId)return;try{const [sources,map]=await Promise.all([api(`/api/projects/${projectId}/sources`),api(`/api/projects/${projectId}/map`)]);$('#sourceList').innerHTML=sources.map(s=>`<article class="source-card"><span class="source-kind">${esc(s.kind)} · ${esc(s.status)}</span><h3>${esc(s.name)}</h3><small>${esc(s.uri||'local upload')}</small></article>`).join('')||'<article class="source-card"><span class="source-kind">EMPTY</span><h3>No sources connected</h3><small>Add GitHub, Drive, a web link or upload documents.</small></article>';const langs=Object.entries(map.languages||{}).map(([k,v])=>`${k}: ${v}`).join('\n');const syms=(map.symbols||[]).slice(0,18).map(s=>`${s.kind||'symbol'}  ${s.name}`).join('\n');$('#repoMap').innerHTML=`<div class="knowledge-number"><b>${map.documents||0}</b><span>indexed files/documents</span></div><h3>Languages</h3><pre>${esc(langs||'—')}</pre><h3>Sample symbols</h3><pre>${esc(syms||'Connect a repository to build the symbol graph.')}</pre>`}catch(e){toast(e.message)}}
$('#knowledgeSearchBtn').onclick=async()=>{const q=$('#knowledgeSearch').value.trim();if(!q||!projectId)return;$('#searchResults').innerHTML='<div class="hit"><b>Searching hybrid index…</b></div>';try{const r=await api('/api/search',{method:'POST',body:JSON.stringify({project_id:projectId,query:q,top_k:12})});$('#searchResults').innerHTML=r.results.map(x=>`<article class="hit"><header><b>${esc(x.source_name)}</b><code>${esc(x.citation||'')}</code></header><p>${esc((x.content||'').slice(0,900))}</p></article>`).join('')||'<div class="hit">No matching evidence.</div>'}catch(e){toast(e.message)}};
$('#knowledgeSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#knowledgeSearchBtn').click()});
$('#openSourceModal').onclick=()=>modal('#sourceModal');$$('[data-source-tab]').forEach(b=>b.onclick=()=>{$$('[data-source-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#sourceLinkPane').classList.toggle('hidden',b.dataset.sourceTab!=='link');$('#sourceFilePane').classList.toggle('hidden',b.dataset.sourceTab!=='file')});
$('#ingestSource').onclick=async()=>{const uri=$('#sourceUrl').value.trim();if(!uri||!projectId)return;const b=$('#ingestSource');b.disabled=true;b.textContent='Indexing…';try{const r=await api('/api/sources/ingest',{method:'POST',body:JSON.stringify({user_id:USER,project_id:projectId,uri,kind:'auto',access_token:$('#sourceToken').value.trim()||null})});toast(`Indexed ${r.files||1} source file(s)`);modal('#sourceModal',false);$('#sourceUrl').value='';$('#sourceToken').value='';await loadKnowledge();await loadHome()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Connect + index'}};
$('#uploadFiles').onclick=async()=>{const files=$('#sourceFiles').files;if(!files.length||!projectId)return;const b=$('#uploadFiles');b.disabled=true;for(const file of files){const fd=new FormData();fd.append('project_id',projectId);fd.append('file',file);try{await api('/api/sources/upload',{method:'POST',body:fd});toast(`Indexed ${file.name}`)}catch(e){toast(`${file.name}: ${e.message}`)}}b.disabled=false;modal('#sourceModal',false);await loadKnowledge();await loadHome()};

async function loadPaths(){if(!projectId)return;try{const rows=await api(`/api/onboarding/${projectId}?user_id=${USER}`);$('#pathDetail').classList.add('hidden');$('#pathList').classList.remove('hidden');$('#pathList').innerHTML=rows.map(p=>`<article class="path-card" data-path="${p.id}"><span class="tag">${esc(p.level)} · ${p.weeks} weeks</span><h3>${esc(p.target_role)}</h3><p>${esc((p.plan?.summary||'Role-specific onboarding generated from the private codebase.').slice(0,160))}</p><div class="path-meta"><span>${p.hours_per_week||8}h / week</span><span>${(p.plan?.modules||[]).length} modules</span><span>${p.is_public?'Shared':'Invite only'}</span></div></article>`).join('')||'<article class="path-card"><span class="tag">START HERE</span><h3>No onboarding paths yet.</h3><p>Generate one after connecting a repository or internal documents.</p></article>';$$('[data-path]').forEach(x=>x.onclick=()=>openPath(x.dataset.path))}catch(e){toast(e.message)}}
async function openPath(id){try{const p=await api(`/api/onboarding/path/${id}?user_id=${USER}`);activePath=p;$('#pathList').classList.add('hidden');const d=$('#pathDetail');d.classList.remove('hidden');const prog=new Map((p.progress_items||[]).map(x=>[x.item_id,x]));const mods=(p.plan.modules||[]).map((m,mi)=>`<article class="panel module"><p class="eyebrow">MODULE ${String(mi+1).padStart(2,'0')}</p><h3>${esc(m.title)}</h3><p class="microcopy">${esc(m.outcome||'')}</p>${(m.items||[]).map(x=>{const st=prog.get(x.id);return`<div class="module-item"><span class="step">${st?.status==='completed'?'✓':mi+1}</span><div><b>${esc(x.title)}</b><small>${esc(x.type||'lesson')} · ${x.minutes||15} min · +${x.xp||100} XP</small></div><button class="secondary complete-item" data-item="${esc(x.id)}">${st?.status==='completed'?'Done':'Complete'}</button></div>`}).join('')}</article>`).join('');const resources=(p.resources||[]).map(r=>`<div class="resource-row"><div><a href="${esc(r.url)}" target="_blank">${esc(r.title)}</a><small>${esc(r.resource_type||r.source||'resource')} · ${esc(r.rationale||'Curated prerequisite resource')}</small></div><span>↗</span></div>`).join('')||'<p class="microcopy">The Browser-Use resource scout is curating YouTube, official docs, engineering blogs and research papers. Refresh after the bridge completes the job.</p>';d.innerHTML=`<button class="secondary back" id="backPaths">← All paths</button><div class="page-head"><div><p class="eyebrow">${esc(p.level.toUpperCase())} · ${p.weeks} WEEKS</p><h1>${esc(p.target_role)}</h1><p>${esc(p.plan.summary||'')}</p></div><div><div class="system-chip">Invite code · ${esc(p.invite_code)}</div></div></div><div class="knowledge-layout"><div>${mods}</div><div><article class="panel"><div class="panel-title"><div><b>Leaderboard</b><small>Checkpoint-weighted XP</small></div></div><div class="leaderboard">${leaderboardHtml(p.members||[])}</div></article><article class="panel" style="margin-top:14px"><div class="panel-title"><div><b>Curated resources</b><small>Public context only</small></div></div>${resources}</article></div></div>`;$('#backPaths').onclick=()=>loadPaths();$$('.complete-item',d).forEach(b=>b.onclick=async()=>{if(b.textContent==='Done')return;try{await api(`/api/onboarding/path/${p.id}/progress`,{method:'POST',body:JSON.stringify({user_id:USER,item_id:b.dataset.item,status:'completed',progress:1,score:1})});toast('+150 XP · progress synced');openPath(p.id);loadHome()}catch(e){toast(e.message)}})}catch(e){toast(e.message)}}
function leaderboardHtml(rows){return rows.slice(0,10).map((r,i)=>`<div class="rank"><span class="num">${i+1}</span><div><strong>${esc(r.display_name||r.user_id)}</strong><small>${fmtPct(r.progress||0)} path progress</small></div><b>${r.xp||0} XP</b></div>`).join('')||'<div class="rank"><span class="num">1</span><div><strong>You</strong><small>Start the first checkpoint</small></div><b>0 XP</b></div>'}
$('#newPathBtn').onclick=()=>modal('#pathModal');$('#generatePath').onclick=async()=>{if(!projectId)return;const b=$('#generatePath');b.disabled=true;b.textContent='Analyzing repository…';try{const p=await api('/api/onboarding',{method:'POST',body:JSON.stringify({user_id:USER,project_id:projectId,target_role:$('#pathRole').value,level:$('#pathLevel').value,weeks:+$('#pathWeeks').value,hours_per_week:+$('#pathHours').value,background:$('#pathBackground').value,is_public:false})});modal('#pathModal',false);toast('Onboarding path generated · resource scout queued');await loadPaths();openPath(p.id);loadHome()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Analyze repository + generate'}};

$$('.mode').forEach(m=>m.onclick=()=>{$$('.mode').forEach(x=>x.classList.toggle('active',x===m));askMode=m.dataset.mode;$('#chatRoute').textContent={auto:'Auto routing',qa:'Direct grounded Q&A',socratic:'Socratic tutor',explain:'Simple explanation',code:'Code reasoning'}[askMode]});
$('#newThreadBtn').onclick=()=>{currentThread=null;$('#chat').innerHTML='<div class="message assistant"><div class="bubble"><b>Fresh thread.</b><p>What do you want to understand?</p></div></div>'};
function addBubble(text,who='assistant',sources=[],metrics=null){const d=document.createElement('div');d.className=`message ${who}`;d.innerHTML=`<div class="bubble">${esc(text).replace(/\n/g,'<br>')}${sources.length?`<div class="sources">${sources.slice(0,5).map(s=>`${esc(s.ref||'')} ${esc(s.citation||s.source_name||'')}`).join(' · ')}</div>`:''}${metrics?.ttft_ms?`<div class="sources">TTFT ${(metrics.ttft_ms/1000).toFixed(2)}s · ${metrics.tokens_per_second?metrics.tokens_per_second.toFixed(1)+' tok/s':'local inference'}</div>`:''}</div>`;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight;return d}
async function sendQuestion(){const q=$('#question').value.trim();if(!q||!projectId)return;addBubble(q,'user');$('#question').value='';const wait=addBubble('Reading the private knowledge layer…');try{const r=await api('/api/ask',{method:'POST',body:JSON.stringify({user_id:USER,project_id:projectId,question:q,thread_id:currentThread,mode:askMode,hint_level:2,allow_final_answer:false})});if(r.mode==='research'){wait.querySelector('.bubble').innerHTML=`Research job queued. Browser-Use is gathering public evidence without receiving private repository context.`;return}currentThread=r.thread_id;wait.remove();addBubble(r.answer,'assistant',r.sources||[],r.metrics);$('#chatRoute').textContent=`${r.mode} · routed locally`;if(r.metrics?.ttft_ms)$('#heroLatency').textContent=`${(r.metrics.ttft_ms/1000).toFixed(2)}s TTFT`}catch(e){wait.querySelector('.bubble').textContent=e.message}}
$('#sendAsk').onclick=sendQuestion;$('#question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendQuestion()}});

async function loadTeam(){try{const [team,stats]=await Promise.all([api(`/api/team?org_id=${ORG}`),api(`/api/admin/stats?org_id=${ORG}`)]);$('#teamList').innerHTML=team.map(u=>`<div class="person"><span class="person-avatar">${esc(u.avatar||u.display_name?.slice(0,2).toUpperCase())}</span><div><strong>${esc(u.display_name)}</strong><small>${esc(u.role_title||'Engineer')} · ${esc(u.email||'local account')}</small></div><span class="system-chip">Active</span></div>`).join('');renderMiniLeaderboard(stats.leaderboard||[]);$('#teamStats').innerHTML=[['Learners',stats.users],['Projects',stats.projects],['Indexed knowledge',stats.documents],['Learning paths',stats.onboarding_paths]].map(([k,v])=>`<article class="stat-card"><b>${v}</b><span>${k}</span></article>`).join('')}catch(e){toast(e.message)}}
$('#inviteBtn').onclick=()=>modal('#inviteModal');$('#createInvite').onclick=async()=>{try{const r=await api('/api/team/invite',{method:'POST',body:JSON.stringify({org_id:ORG,invited_by:USER,email:$('#inviteEmail').value||null,role_title:$('#inviteRole').value||'Engineer'})});const url=`${location.origin}/?invite=${encodeURIComponent(r.token)}`;$('#inviteResult').classList.remove('hidden');$('#inviteResult').innerHTML=`Share this local/private invite:<br><b>${esc(url)}</b>`;navigator.clipboard?.writeText(url);toast('Invite link copied')}catch(e){toast(e.message)}};

async function loadEngineering(){try{const [stats,traces,comp,h]=await Promise.all([api(`/api/admin/stats?org_id=${ORG}`),api('/api/admin/traces?limit=80'),api('/api/admin/competition'),api('/api/health')]);const q=comp.summary?.socratic_quality||{}, sp=comp.summary?.speculative_decoding||{};const cards=comp.available!==false&&comp.summary?[['Socratic quality',`${Number(q.tuned_score||0).toFixed(1)}/100`,q.score_delta_points?`+${Number(q.score_delta_points).toFixed(1)} pts vs base`:'held-out evaluation'],['Decode throughput',`${Number(sp.spec_decode_tok_s_p50||0).toFixed(1)} tok/s`,sp.decode_tok_s_change_pct!=null?`${Number(sp.decode_tok_s_change_pct).toFixed(1)}% vs standard`:'spec benchmark'],['TTFT',`${Number(sp.spec_ttft_p50_s||0).toFixed(2)}s`,'p50 speculative profile']]:[['Fine-tune','Awaiting run','make competition'],['Model throughput','Awaiting run','measured on DGX Spark'],['Agent traces',String(stats.agent_traces||0),'stored locally']];$('#engineeringCards').innerHTML=cards.map(([a,b,c])=>`<article class="eng-card"><p class="eyebrow">${esc(a)}</p><div class="metric">${esc(b)}</div><span class="delta">${esc(c)}</span><p>No benchmark value is fabricated. Competition metrics are read from the Spark run artifacts.</p></article>`).join('');$('#traceList').innerHTML=traces.map(t=>`<div class="trace"><span class="agent">${esc(t.agent)}</span><span class="preview">${esc(t.prompt_preview||'')}</span><b>${t.ttft_ms?`${(t.ttft_ms/1000).toFixed(2)}s TTFT`:'—'}</b><b>${t.tokens_per_second?`${t.tokens_per_second.toFixed(1)} t/s`:'—'}</b></div>`).join('')||'<div class="trace"><span class="agent">No traces yet</span><span class="preview">Ask StudyBuddy a question to populate the local trace store.</span></div>'}catch(e){toast(e.message)}}

$('#newProjectBtn').onclick=()=>modal('#projectModal');$('#createProject').onclick=async()=>{const name=$('#projectName').value.trim();if(!name)return;try{const p=await api('/api/projects',{method:'POST',body:JSON.stringify({org_id:ORG,user_id:USER,name,description:$('#projectDescription').value})});projectId=p.id;localStorage.setItem('spartan_project',projectId);modal('#projectModal',false);await ensureProject();refreshAll();toast('Workspace created')}catch(e){toast(e.message)}};

function connectWS(){try{const u=new URL(API),ws=new WebSocket(`${u.protocol==='https:'?'wss':'ws'}://${u.host}/ws/${USER}`);ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(['progress','resource_session','agent_job'].includes(m.kind)){loadHome();if(m.kind==='agent_job')loadPaths()}}catch{}};ws.onopen=()=>setInterval(()=>{if(ws.readyState===1)ws.send('ping')},25000);ws.onclose=()=>setTimeout(connectWS,3000)}catch{}}
async function refreshAll(){await Promise.all([health(),loadHome(),loadKnowledge()])}
async function boot(){await ensureProject();await refreshAll();connectWS();const invite=new URLSearchParams(location.search).get('invite');if(invite)toast(`Invite detected: ${invite} · teammate acceptance API is ready`)}
boot();
