global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: studybuddy-backend
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: vllm-teacher
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8101"]
  - job_name: vllm-embeddings
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8105"]
